### ISSUE TITLE
Update Home Page

### ISSUE THREAD

**Issue by coverbeck** [BD2KGenomics/dcc-dashboard#44]
Home page still has references to workflows and ordering, which is not applicable.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DASH-13)
┆Project Name: CGP-Dashboard
┆Issue Number: DASH-13

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

[~casloan], did you say you have an example that combines two grants?

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Had discussion with [~casloan] , some requirements and ideas:

  * Add Data Commons/Stage logo
  * Update Mission Statement
  * Should have a section for Getting Started
  * Change footer link to cgp instead of cgl
  * Use phrase like `Explore and export research data`.
  * We need an email address for contact (should not be a personal email address); need new ticket to create one.
  * Instead of `Boardwalk` on the top level menu, call it `Data Browser`.
  * Text say something like `The portal is based on the azul indexer`.
  * This should be configurable, so we can skin it for different uses, although the first iteration may not be quite as configurable.

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

[~casloan] Added you as a reviewer to the PR: [https://github.com/DataBiosphere/cgp-dashboard/pull/60](https://github.com/DataBiosphere/cgp-dashboard/pull/60)
